version: "3"
services:
  frontend:
    build: ./client
    ports: 
      - "3000:80"
    environment:
      - API_ENDPOINT=http://localhost:5020
  backend:
    build: ./server
    ports:
      - "5020:5010"
    env_file:
      - ./server/config.env

      
    
