version: "3"
services:
  frontend:
    build: ./client
    ports: 
      - "3000:3000"
    env_file:
      - ./client/config.env
  backend:
    build: ./server
    ports:
      - "5010:5010"
    env_file:
      - ./server/config.env

      
    
