version: "3"
services:
  frontend:
    build: ./client
    ports: 
      - "3000:80"
    environment:
      - API_ENDPOINT=http://localhost:5080
  backend:
    build: ./server
    ports:
      - "5080:5020"
    env_file:
      - ./server/config.env
    environment:
      - PORT=5020

      
    
