version: "3"
services:
  frontend:
    build: ./client
    ports: 
      - "3000:80"
    environment:
      - API_ENDPOINT=http://localhost:5020
  backend:
    build: ./server
    ports:
      - "5080:5020"
    environment:
      - PORT=5020
      - MONGODB_URI=mongodb+srv://cluster0.abcdef.mongodb.net
      - MONGODB_PASSWORD=whatever
      - MONGODB_USER=whatever
  

      
    
