alertmanager:
  enabled: false

grafana:
  grafana.ini:
    server:
      # root_url: "%(protocol)s://%(domain)s/monitoring-grafana"
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: true
    path: /grafana
    pathType: ImplementationSpecific
    annotations:
      kubernetes.io/ingress.class: nginx
prometheusOperator:
  enabled: true

  ## Prometheus-Operator v0.39.0 and later support TLS natively.
  ##
  tls:
    enabled: false
  admissionWebhooks:
    failurePolicy: Fail
    enabled: false
    patch:
      enabled: true

